version: '3'

x-base: &base
    env_file:
        - .env

services:
  mysql:
    image: mysql:latest
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - ${MYSQL_PORT}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  celery:
    build: ./django_app
    container_name: 'celery'
    command: celery -A config  worker -l info
    env_file:
      - .env
    volumes:
      - ./django_app:/usr/src/app
    depends_on:
      - django_app
      - redis
      - mysql

  dashboard:
    build: ./django_app
    image: mher/flower:latest
    command: celery -A config flower --port=${FLOWER_PORT} --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - .env
    depends_on:
      - django_app
      - redis
      - celery

  redis:
    image: redis
    container_name: 'redis'
    volumes:
      - ./redis/data:/data
    expose:
      - ${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  django_app:
      build:
        context: django_app
      command: uwsgi --strict --ini uwsgi.ini
      container_name: django_app
      env_file:
          - .env
      depends_on:
        mysql:
          condition: service_healthy
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8000"]
        interval: 30s
        timeout: 10s
        retries: 5
      expose:
        - "${DJANGO_PORT}"

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/templates:ro
      - ./nginx/logs:/etc/nginx/logs
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
      NGINX_SET_REAL_IP_FROM: 192.168.1.0/24
      DJANGO_PORT: ${DJANGO_PORT}
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - django_app

volumes:
  mysql-data:
    name: mysql_data