# Generated by Django 4.2.4 on 2023-09-04 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='expired_date',
            new_name='access_expired_date',
        ),
        migrations.AddField(
            model_name='token',
            name='refresh_expired_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
