# Generated by Django 4.2.4 on 2023-09-02 20:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('phone_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenotification',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number'),
        ),
    ]
