# Generated by Django 4.2.4 on 2023-09-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_notifications', '0002_alter_phonenotification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenotification',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_notification', to='phone_notifications.mailing'),
        ),
    ]
